
package com.isima.jee.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BiblioServiceService", targetNamespace = "http://ws.jee.isima.com/", wsdlLocation = "http://localhost:8888/biblio/BiblioServiceService.wsdl")
public class BiblioServiceService
    extends Service
{

    private final static URL BIBLIOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BIBLIOSERVICESERVICE_EXCEPTION;
    private final static QName BIBLIOSERVICESERVICE_QNAME = new QName("http://ws.jee.isima.com/", "BiblioServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/biblio/BiblioServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIBLIOSERVICESERVICE_WSDL_LOCATION = url;
        BIBLIOSERVICESERVICE_EXCEPTION = e;
    }

    public BiblioServiceService() {
        super(__getWsdlLocation(), BIBLIOSERVICESERVICE_QNAME);
    }

    public BiblioServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIBLIOSERVICESERVICE_QNAME, features);
    }

    public BiblioServiceService(URL wsdlLocation) {
        super(wsdlLocation, BIBLIOSERVICESERVICE_QNAME);
    }

    public BiblioServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIBLIOSERVICESERVICE_QNAME, features);
    }

    public BiblioServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BiblioServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BiblioService
     */
    @WebEndpoint(name = "BiblioServicePort")
    public BiblioService getBiblioServicePort() {
        return super.getPort(new QName("http://ws.jee.isima.com/", "BiblioServicePort"), BiblioService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BiblioService
     */
    @WebEndpoint(name = "BiblioServicePort")
    public BiblioService getBiblioServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jee.isima.com/", "BiblioServicePort"), BiblioService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIBLIOSERVICESERVICE_EXCEPTION!= null) {
            throw BIBLIOSERVICESERVICE_EXCEPTION;
        }
        return BIBLIOSERVICESERVICE_WSDL_LOCATION;
    }

}
